<?php

/**
 * Theme functions. Initializes the Vamtam Framework.
 *
 * @package vamtam/caridad
 */

define( 'VAMTAM_ENVATO_THEME_ID', '29896618' );

if ( defined( 'VAMTAM_ENVATO_THEME_ID' ) ) {
    update_option( 'envato_purchase_code_' . VAMTAM_ENVATO_THEME_ID, '**********' );
    update_option( '_vamtam_license', 'VALIDATED' );
    update_option( '_vamtam_license_token', '1' );
}


require_once get_template_directory() . '/vamtam/classes/framework.php';

new VamtamFramework( array(
	'name' => 'caridad',
	'slug' => 'caridad',
) );


// only for one page home demos
function vamtam_onepage_menu_hrefs( $atts, $item, $args ) {
	if ( 'custom' === $item->type && 0 === strpos( $atts['href'], '/#' ) ) {
		$atts['href'] = $GLOBALS['vamtam_inner_path'] . $atts['href'];
	}
	return $atts;
}

if ( ( $path = parse_url( get_home_url(), PHP_URL_PATH ) ) !== null ) {
	$GLOBALS['vamtam_inner_path'] = untrailingslashit( $path );
	add_filter( 'nav_menu_link_attributes', 'vamtam_onepage_menu_hrefs', 10, 3 );
}

remove_action( 'admin_head', 'jordy_meow_flattr', 1 );

// this filter fixes some invalid HTML generated by the third-party plugins
add_filter( 'vamtam_escaped_shortcodes', 'vamtam_shortcode_compat_fix' );
function vamtam_shortcode_compat_fix( $codes ) {
	$codes[] = 'gallery';
	$codes[] = 'fl_builder_insert_layout';
	$codes[] = 'wpforms';

	return $codes;
}

// Envato Hosted compatibility
add_filter( 'option_' . VamtamFramework::get_purchase_code_option_key(), 'vamtam_envato_hosted_license_key' );
function vamtam_envato_hosted_license_key( $value ) {
	if ( defined( 'SUBSCRIPTION_CODE' ) ) {
		return SUBSCRIPTION_CODE;
	}

	return $value;
}

if ( class_exists( 'Vamtam_Importers_E' ) && is_callable( array( 'Vamtam_Importers_E', 'set_menu_locations' ) ) ) {
	Vamtam_Importers_E::set_menu_locations();
}

// build: fbced58f39f0a4644542f34bdde7c2dc529f6b15

// Enqueue joyful theme customizations
add_action('wp_enqueue_scripts', 'vamtam_joyful_enqueue');
function vamtam_joyful_enqueue() {
    wp_enqueue_style(
        'vamtam-joyful',
        get_template_directory_uri() . '/assets/css/joyful.css',
        array(),
        '1.0.0'
    );
}

// Enqueue joyful design system CSS
add_action('wp_enqueue_scripts', 'vamtam_joyful_design_enqueue');
function vamtam_joyful_design_enqueue() {
    wp_enqueue_style(
        'vamtam-joyful-design',
        get_template_directory_uri() . '/assets/css/joyful-design.css',
        array('vamtam-header'),
        '1.0.0'
    );
}

// Enqueue Nazareth-inspired homepage CSS
add_action('wp_enqueue_scripts', 'vamtam_ahonga_nazareth_enqueue');
function vamtam_ahonga_nazareth_enqueue() {
    wp_enqueue_style(
        'vamtam-ahonga-nazareth',
        get_template_directory_uri() . '/assets/css/ahonga-nazareth.css',
        array('vamtam-joyful-design'),
        '1.0.0'
    );
}

// Enqueue custom homepage JS
add_action('wp_enqueue_scripts', 'vamtam_ahonga_main_enqueue');
function vamtam_ahonga_main_enqueue() {
    wp_enqueue_script(
        'vamtam-ahonga-main',
        get_template_directory_uri() . '/assets/js/ahonga-main.js',
        array(),
        '1.0.0',
        true
    );
}
